<?php
namespace App\Services;
use App\Models\{Company,Currency,ExchangeRate,SalesInvoice,PurchaseBill,FxRevaluationItem,Account};
use App\Support\Decimal;
use Brick\Math\BigDecimal;
use Brick\Math\RoundingMode;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class FxRevaluationService {
 public function run(int $companyId,int $userId,string $date):?\App\Models\Journal{return DB::transaction(function()use($companyId,$userId,$date){app(PeriodService::class)->forDate($companyId,$date,true);$company=Company::findOrFail($companyId);$lines=[];$items=[];$baseCurrency=$company->base_currency_id;
  foreach([[SalesInvoice::class,'sales','invoice_date','credit_of_invoice_id','receivable'],[PurchaseBill::class,'purchase','bill_date','credit_of_bill_id','payable']] as [$class,$method,$dateCol,$creditCol,$kind]){$docs=$class::where('company_id',$companyId)->where('status','posted')->whereNull($creditCol)->where('currency_id','<>',$baseCurrency)->whereDate($dateCol,'<=',$date)->lockForUpdate()->get();foreach($docs as $doc){$bal=app(DocumentBalanceService::class)->{$method}($doc,$date);if(Decimal::cmp($bal['foreign'],'0')<=0)continue;$rate=ExchangeRate::where('company_id',$companyId)->where('currency_id',$doc->currency_id)->whereDate('rate_date','<=',$date)->orderByDesc('rate_date')->first();if(!$rate)throw ValidationException::withMessages(['exchange_rate'=>'Missing period-end exchange rate for a foreign currency.']);$target=BigDecimal::of($bal['foreign'])->multipliedBy($rate->rate)->toScale(3,RoundingMode::HALF_UP);$current=BigDecimal::of($bal['base']);$adj=$target->minus($current)->toScale(3,RoundingMode::HALF_UP);if($adj->isZero())continue;$control=$doc->control_account_id;$this->assertAccount($companyId,$control,'control account');$gain=$adj->isPositive()?($kind==='receivable'):$kind==='payable'; // positive AR or negative AP is gain
    if($kind==='payable')$gain=$adj->isNegative();
    $amount=(string)$adj->abs();if($kind==='receivable')$lines[]=['account_id'=>$control,'description'=>'FX revaluation','debit'=>$adj->isPositive()?$amount:'0','credit'=>$adj->isNegative()?$amount:'0'];else $lines[]=['account_id'=>$control,'description'=>'FX revaluation','debit'=>$adj->isNegative()?$amount:'0','credit'=>$adj->isPositive()?$amount:'0'];$fxAccount=$gain?$company->fx_gain_account_id:$company->fx_loss_account_id;$this->assertAccount($companyId,$fxAccount,$gain?'FX gain account':'FX loss account');$lines[]=['account_id'=>$fxAccount,'description'=>'Unrealized FX '.($gain?'gain':'loss'),'debit'=>$gain?'0':$amount,'credit'=>$gain?$amount:'0'];$items[]=[$doc,$bal,(string)$target,(string)$adj];}}
  if(!$items)return null;$j=app(JournalService::class)->createDraft($companyId,$userId,$date,'Period-end FX revaluation',$lines,['source_type'=>'fx_revaluation']);$j=app(JournalService::class)->post($j,$userId);foreach($items as [$doc,$bal,$target,$adj])FxRevaluationItem::create(['company_id'=>$companyId,'journal_id'=>$j->id,'revaluable_type'=>get_class($doc),'revaluable_id'=>$doc->id,'currency_id'=>$doc->currency_id,'revaluation_date'=>$date,'foreign_outstanding'=>$bal['foreign'],'previous_carrying_base'=>$bal['base'],'target_carrying_base'=>$target,'carrying_adjustment'=>$adj]);app(AuditService::class)->record('fx.revalued',$j,null,['items'=>count($items)],$companyId,$userId);return $j;});}
 private function assertAccount(int $companyId,?int $id,string $name):void{if(!$id||!Account::where('company_id',$companyId)->whereKey($id)->where('active',true)->where('is_postable',true)->exists())throw ValidationException::withMessages(['account'=>$name.' is not configured.']);}
}