<?php
namespace App\Services;
use App\Models\{Account,Journal,JournalLine,Company};
use App\Support\Decimal;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class JournalService {
 public function createDraft(int $companyId,int $userId,string $date,?string $description,array $lines,array $meta=[]):Journal{return DB::transaction(function()use($companyId,$userId,$date,$description,$lines,$meta){$p=app(PeriodService::class)->forDate($companyId,$date,false);$j=Journal::create(['company_id'=>$companyId,'accounting_period_id'=>$p->id,'journal_number'=>app(SequenceService::class)->next($companyId,'journal','JV-'),'entry_date'=>$date,'description'=>$description,'status'=>'draft','source_type'=>$meta['source_type']??null,'source_id'=>$meta['source_id']??null,'exclude_from_profit_loss'=>$meta['exclude_from_profit_loss']??false,'created_by'=>$userId]);$this->replaceLines($j,$lines);return $j->fresh('lines');});}
 public function replaceLines(Journal $j,array $lines):Journal{if($j->status!=='draft')throw ValidationException::withMessages(['journal'=>'Only draft journals may be edited.']); $this->assertCompany($j); return DB::transaction(function()use($j,$lines){$j->lines()->delete(); foreach(array_values($lines) as $i=>$line){JournalLine::create(['journal_id'=>$j->id,'line_no'=>$i+1,'account_id'=>$line['account_id'],'description'=>$line['description']??null,'debit'=>Decimal::money($line['debit']??'0'),'credit'=>Decimal::money($line['credit']??'0'),'currency_id'=>$line['currency_id']??null,'exchange_rate'=>$line['exchange_rate']??null,'foreign_amount'=>$line['foreign_amount']??null]);} return $j->fresh('lines');});}
 public function post(Journal $j,int $userId):Journal{return DB::transaction(function()use($j,$userId){$j=Journal::whereKey($j->id)->lockForUpdate()->with('lines')->firstOrFail();$this->assertCompany($j);if($j->status!=='draft')throw ValidationException::withMessages(['journal'=>'Journal is not draft.']);app(PeriodService::class)->forDate($j->company_id,$j->entry_date,true);$this->validateLines($j);$j->update(['status'=>'posted','posted_by'=>$userId,'posted_at'=>now()]);app(AuditService::class)->record('journal.posted',$j,['status'=>'draft'],['status'=>'posted'],$j->company_id,$userId);return $j->fresh('lines');});}
 public function reverse(Journal $original,int $userId,string $date,?string $reason=null):Journal{return DB::transaction(function()use($original,$userId,$date,$reason){$original=Journal::whereKey($original->id)->lockForUpdate()->with('lines')->firstOrFail();$this->assertCompany($original);if($original->status!=='posted')throw ValidationException::withMessages(['journal'=>'Only posted journals may be reversed.']);app(PeriodService::class)->forDate($original->company_id,$date,true);$lines=$original->lines->map(fn($l)=>['account_id'=>$l->account_id,'description'=>'Reversal: '.($l->description??''),'debit'=>$l->credit,'credit'=>$l->debit,'currency_id'=>$l->currency_id,'exchange_rate'=>$l->exchange_rate,'foreign_amount'=>$l->foreign_amount===null?null:(string)\Brick\Math\BigDecimal::of((string)$l->foreign_amount)->negated()])->all();$rev=$this->createDraft($original->company_id,$userId,$date,$reason?:'Reversal of '.$original->journal_number,$lines,['source_type'=>'journal_reversal','source_id'=>$original->id,'exclude_from_profit_loss'=>$original->exclude_from_profit_loss]);$rev->reversal_of_journal_id=$original->id;$rev->save();$rev=$this->post($rev,$userId);$original->update(['status'=>'reversed','reversed_at'=>now()]);app(AuditService::class)->record('journal.reversed',$original,['status'=>'posted'],['status'=>'reversed','reversal_journal_id'=>$rev->id],$original->company_id,$userId);return $rev;});}
 private function validateLines(Journal $j):void{if($j->lines->count()<2)throw ValidationException::withMessages(['lines'=>'A posted journal requires at least two lines.']);$debit='0.000';$credit='0.000';foreach($j->lines as $l){$a=Account::where('company_id',$j->company_id)->whereKey($l->account_id)->first();if(!$a||!$a->active||!$a->is_postable)throw ValidationException::withMessages(['lines'=>'Every journal line must use an active postable account from the same company.']);$d=Decimal::money($l->debit);$c=Decimal::money($l->credit);if((Decimal::cmp($d,'0')>0)===(Decimal::cmp($c,'0')>0))throw ValidationException::withMessages(['lines'=>'Each line must contain exactly one positive debit or credit.']);$debit=Decimal::add($debit,$d);$credit=Decimal::add($credit,$c);}if(Decimal::cmp($debit,'0')<=0||Decimal::cmp($debit,$credit)!==0)throw ValidationException::withMessages(['lines'=>'Journal debits and credits must be equal and greater than zero.']);}
 private function assertCompany(Journal $j):void{if(auth()->check()&&auth()->user()->company_id!==$j->company_id)abort(404);}
}