<?php
namespace App\Services;
use App\Models\{Payment,PaymentAllocation,SalesInvoice,PurchaseBill,Account,Company,Contact};
use App\Support\Decimal;
use Brick\Math\BigDecimal;
use Brick\Math\RoundingMode;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class PaymentService {
 public function receive(int $companyId,int $userId,array $data,array $allocations):Payment{return $this->postPayment('receipt',$companyId,$userId,$data,$allocations);}
 public function paySupplier(int $companyId,int $userId,array $data,array $allocations):Payment{return $this->postPayment('supplier_payment',$companyId,$userId,$data,$allocations);}
 private function postPayment(string $type,int $companyId,int $userId,array $data,array $allocations):Payment{return DB::transaction(function()use($type,$companyId,$userId,$data,$allocations){app(PeriodService::class)->forDate($companyId,$data['payment_date'],true);$company=Company::findOrFail($companyId);$contact=Contact::where('company_id',$companyId)->findOrFail($data['contact_id']);$cash=Account::where('company_id',$companyId)->whereKey($data['cash_account_id'])->where('active',true)->where('is_postable',true)->firstOrFail();$rate=BigDecimal::of((string)$data['exchange_rate']);if($rate->isLessThanOrEqualTo(0))throw ValidationException::withMessages(['exchange_rate'=>'Exchange rate must be positive.']);if(empty($allocations))throw ValidationException::withMessages(['allocations'=>'At least one allocation is required.']);$model=$type==='receipt'?SalesInvoice::class:PurchaseBill::class;$balanceMethod=$type==='receipt'?'sales':'purchase';$sumForeign=BigDecimal::zero();$sumSettlement=BigDecimal::zero();$sumCarrying=BigDecimal::zero();$prepared=[];$journalLines=[];$gain=BigDecimal::zero();$loss=BigDecimal::zero();
  foreach($allocations as $row){$doc=$model::where('company_id',$companyId)->whereKey($row['document_id'])->lockForUpdate()->firstOrFail();if($doc->status!=='posted'||($type==='receipt'&&$doc->credit_of_invoice_id)||($type!=='receipt'&&$doc->credit_of_bill_id))throw ValidationException::withMessages(['allocations'=>'Allocations require posted original documents.']);if($doc->contact_id!=$contact->id||$doc->currency_id!=(int)$data['currency_id'])throw ValidationException::withMessages(['allocations'=>'All allocations must match the payment contact and currency.']);$out=app(DocumentBalanceService::class)->{$balanceMethod}($doc,$data['payment_date']);$amount=BigDecimal::of((string)$row['amount'])->toScale(3,RoundingMode::HALF_UP);if($amount->isLessThanOrEqualTo(0)||$amount->compareTo($out['foreign'])>0)throw ValidationException::withMessages(['allocations'=>'Allocation exceeds outstanding amount.']);$outForeign=BigDecimal::of($out['foreign']);$outBase=BigDecimal::of($out['base']);$carrying=$amount->compareTo($outForeign)===0?$outBase:$outBase->multipliedBy($amount)->dividedBy($outForeign,3,RoundingMode::HALF_UP);$settlement=$amount->multipliedBy($rate)->toScale(3,RoundingMode::HALF_UP);$realized=$type==='receipt'?$settlement->minus($carrying):$carrying->minus($settlement);if($realized->isPositive())$gain=$gain->plus($realized);elseif($realized->isNegative())$loss=$loss->plus($realized->abs());$sumForeign=$sumForeign->plus($amount);$sumSettlement=$sumSettlement->plus($settlement);$sumCarrying=$sumCarrying->plus($carrying);$prepared[]=[$doc,$amount,$carrying,$realized];$journalLines[]=['account_id'=>$doc->control_account_id,'description'=>'Settlement '.$doc->getKey(),'debit'=>$type==='receipt'?'0':(string)$carrying,'credit'=>$type==='receipt'?(string)$carrying:'0'];}
  $declared=BigDecimal::of((string)$data['amount'])->toScale(3,RoundingMode::HALF_UP);if($declared->compareTo($sumForeign)!==0)throw ValidationException::withMessages(['amount'=>'Payment amount must equal allocated amount.']);$journalLines[]=['account_id'=>$cash->id,'description'=>'Cash/bank','debit'=>$type==='receipt'?(string)$sumSettlement:'0','credit'=>$type==='receipt'?'0':(string)$sumSettlement];if($gain->isPositive()){$this->assertConfigured($companyId,$company->fx_gain_account_id,'FX gain account');$journalLines[]=['account_id'=>$company->fx_gain_account_id,'description'=>'Realized FX gain','debit'=>'0','credit'=>(string)$gain];}if($loss->isPositive()){$this->assertConfigured($companyId,$company->fx_loss_account_id,'FX loss account');$journalLines[]=['account_id'=>$company->fx_loss_account_id,'description'=>'Realized FX loss','debit'=>(string)$loss,'credit'=>'0'];}
  $p=Payment::create(['company_id'=>$companyId,'contact_id'=>$contact->id,'payment_number'=>app(SequenceService::class)->next($companyId,'payment',$type==='receipt'?'RCPT-':'PAY-'),'type'=>$type,'payment_date'=>$data['payment_date'],'currency_id'=>$data['currency_id'],'amount'=>(string)$sumForeign,'exchange_rate'=>(string)$rate,'base_amount'=>(string)$sumSettlement,'cash_account_id'=>$cash->id,'status'=>'draft','journal_id'=>null,'created_by'=>$userId]);$j=app(JournalService::class)->createDraft($companyId,$userId,$data['payment_date'],$type==='receipt'?'Customer receipt':'Supplier payment',$journalLines,['source_type'=>$type,'source_id'=>$p->id]);$j=app(JournalService::class)->post($j,$userId);$p->update(['status'=>'posted','journal_id'=>$j->id]);foreach($prepared as [$doc,$amount,$carrying,$realized])PaymentAllocation::create(['payment_id'=>$p->id,'allocatable_type'=>get_class($doc),'allocatable_id'=>$doc->id,'amount'=>(string)$amount,'base_amount'=>(string)$carrying,'realized_fx'=>(string)$realized]);app(AuditService::class)->record('payment.posted',$p,null,['journal_id'=>$j->id],$companyId,$userId);return $p->fresh('allocations');},5);}
 public function void(Payment $payment,int $userId,string $date,string $reason):Payment{return DB::transaction(function()use($payment,$userId,$date,$reason){$payment=Payment::whereKey($payment->id)->lockForUpdate()->firstOrFail();if($payment->status!=='posted')throw ValidationException::withMessages(['payment'=>'Only posted payments may be voided.']);$rev=app(JournalService::class)->reverse($payment->journal,$userId,$date,$reason);$payment->update(['status'=>'voided','void_date'=>$date,'voided_at'=>now(),'reversal_journal_id'=>$rev->id]);app(AuditService::class)->record('payment.voided',$payment,['status'=>'posted'],['status'=>'voided','reversal_journal_id'=>$rev->id],$payment->company_id,$userId);return $payment;});}
 private function assertConfigured(int $companyId,?int $id,string $name):void{if(!$id||!Account::where('company_id',$companyId)->whereKey($id)->where('active',true)->where('is_postable',true)->exists())throw ValidationException::withMessages(['account'=>$name.' is not configured.']);}
}