<?php
namespace App\Services;
use App\Models\{PurchaseBill,PurchaseBillLine,Contact,Account,Currency,Company,TaxCode};
use App\Support\Decimal;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class PurchaseService {
 public function createDraft(int $companyId,int $userId,array $data,array $lines):PurchaseBill{return DB::transaction(function()use($companyId,$data,$lines){$contact=Contact::where('company_id',$companyId)->whereKey($data['contact_id'])->whereIn('type',['supplier','both'])->where('active',true)->firstOrFail();$currency=Currency::whereKey($data['currency_id'])->where('active',true)->firstOrFail();$calc=app(DocumentMathService::class)->calculate($companyId,$lines);$bill=PurchaseBill::create(['company_id'=>$companyId,'contact_id'=>$contact->id,'bill_number'=>app(SequenceService::class)->next($companyId,!empty($data['credit_of_bill_id'])?'purchase_credit':'purchase_bill',!empty($data['credit_of_bill_id'])?'PCN-':'BILL-'),'supplier_reference'=>$data['supplier_reference']??null,'bill_date'=>$data['bill_date'],'due_date'=>$data['due_date']??null,'currency_id'=>$currency->id,'exchange_rate'=>$data['exchange_rate']??'1','subtotal'=>$calc['subtotal'],'tax_total'=>$calc['tax_total'],'total'=>$calc['total'],'base_total'=>'0.000','status'=>'draft','credit_of_bill_id'=>$data['credit_of_bill_id']??null]);foreach($calc['lines'] as $l){$this->assertExpenseAccount($companyId,$l['expense_account_id']);PurchaseBillLine::create(['purchase_bill_id'=>$bill->id,'line_no'=>$l['line_no'],'description'=>$l['description'],'quantity'=>$l['quantity'],'unit_price'=>$l['unit_price'],'line_subtotal'=>$l['line_subtotal'],'expense_account_id'=>$l['expense_account_id'],'tax_code_id'=>$l['tax_code_id']??null,'tax_amount'=>$l['tax_amount']]);}return $bill->fresh('lines');});}
 public function createCredit(PurchaseBill $original,int $userId,array $data,array $lines):PurchaseBill{return DB::transaction(function()use($original,$userId,$data,$lines){$original=PurchaseBill::whereKey($original->id)->lockForUpdate()->firstOrFail();if($original->status!=='posted'||$original->credit_of_bill_id)throw ValidationException::withMessages(['bill'=>'Only posted original bills may be credited.']);$data['contact_id']=$original->contact_id;$data['currency_id']=$original->currency_id;$data['credit_of_bill_id']=$original->id;$out=app(DocumentBalanceService::class)->purchase($original,$data['bill_date']);$credit=$this->createDraft($original->company_id,$userId,$data,$lines);if(Decimal::cmp($credit->total,$out['foreign'])>0)throw ValidationException::withMessages(['total'=>'Credit exceeds outstanding bill amount.']);return $credit;});}
 public function post(PurchaseBill $bill,int $userId):PurchaseBill{return DB::transaction(function()use($bill,$userId){$bill=PurchaseBill::whereKey($bill->id)->lockForUpdate()->with('lines')->firstOrFail();if($bill->status!=='draft')throw ValidationException::withMessages(['bill'=>'Bill is not draft.']);app(PeriodService::class)->forDate($bill->company_id,$bill->bill_date,true);$company=Company::findOrFail($bill->company_id);$contact=Contact::where('company_id',$bill->company_id)->findOrFail($bill->contact_id);$control=$contact->payable_account_id?:$company->ap_control_account_id;$this->assertAccount($bill->company_id,$control,'AP control account');$journalLines=[];$base='0.000';foreach($bill->lines as $l){$this->assertExpenseAccount($bill->company_id,$l->expense_account_id);$v=Decimal::mul($l->line_subtotal,$bill->exchange_rate);$base=Decimal::add($base,$v);$journalLines[]=['account_id'=>$l->expense_account_id,'description'=>$l->description,'debit'=>$bill->credit_of_bill_id?'0':$v,'credit'=>$bill->credit_of_bill_id?$v:'0'];if(Decimal::cmp($l->tax_amount,'0')>0){$tax=TaxCode::where('company_id',$bill->company_id)->findOrFail($l->tax_code_id);$taxAcc=$tax->purchase_account_id?:$company->purchase_tax_account_id;$this->assertAccount($bill->company_id,$taxAcc,'purchase tax account');$tv=Decimal::mul($l->tax_amount,$bill->exchange_rate);$base=Decimal::add($base,$tv);$journalLines[]=['account_id'=>$taxAcc,'description'=>'Purchase tax','debit'=>$bill->credit_of_bill_id?'0':$tv,'credit'=>$bill->credit_of_bill_id?$tv:'0'];}}
  $journalLines[]=['account_id'=>$control,'description'=>$bill->bill_number,'debit'=>$bill->credit_of_bill_id?$base:'0','credit'=>$bill->credit_of_bill_id?'0':$base,'currency_id'=>$bill->currency_id,'exchange_rate'=>$bill->exchange_rate,'foreign_amount'=>$bill->credit_of_bill_id?('-'.$bill->total):$bill->total];$j=app(JournalService::class)->createDraft($bill->company_id,$userId,(string)$bill->bill_date,'Purchase '.$bill->bill_number,$journalLines,['source_type'=>$bill->credit_of_bill_id?'purchase_credit':'purchase_bill','source_id'=>$bill->id]);$j=app(JournalService::class)->post($j,$userId);$bill->update(['status'=>'posted','journal_id'=>$j->id,'control_account_id'=>$control,'base_total'=>$base]);app(AuditService::class)->record('purchase.posted',$bill,['status'=>'draft'],['status'=>'posted','journal_id'=>$j->id],$bill->company_id,$userId);return $bill->fresh('lines');});}
 private function assertExpenseAccount(int $companyId,int $accountId):void{$a=Account::where('company_id',$companyId)->findOrFail($accountId);if(!$a->active||!$a->is_postable||!in_array($a->type,['expense','asset']))throw ValidationException::withMessages(['account'=>'Purchase lines require an active postable expense/asset account.']);}
 private function assertAccount(int $companyId,?int $id,string $label):void{if(!$id||!Account::where('company_id',$companyId)->whereKey($id)->where('active',true)->where('is_postable',true)->exists())throw ValidationException::withMessages(['account'=>$label.' is not configured correctly.']);}
}