<?php
namespace App\Services;
use App\Models\{Account,SalesInvoice,PurchaseBill};
use App\Support\Decimal;
use Illuminate\Support\Facades\DB;
class ReportService {
 public function trialBalance(int $companyId,string $from,string $to):array{return DB::table('accounts')->leftJoin('journal_lines','journal_lines.account_id','=','accounts.id')->leftJoin('journals',function($j)use($companyId,$from,$to){$j->on('journals.id','=','journal_lines.journal_id')->where('journals.company_id','=',$companyId)->whereIn('journals.status',['posted','reversed'])->whereBetween('journals.entry_date',[$from,$to]);})->where('accounts.company_id',$companyId)->groupBy('accounts.id','accounts.code','accounts.name_en','accounts.type')->orderBy('accounts.code')->selectRaw('accounts.id,accounts.code,accounts.name_en,accounts.type,COALESCE(SUM(CASE WHEN journals.id IS NOT NULL THEN journal_lines.debit ELSE 0 END),0) debit,COALESCE(SUM(CASE WHEN journals.id IS NOT NULL THEN journal_lines.credit ELSE 0 END),0) credit')->get()->map(fn($r)=>(array)$r)->all();}
 public function generalLedger(int $companyId,int $accountId,string $from,string $to):array{return DB::table('journal_lines')->join('journals','journals.id','=','journal_lines.journal_id')->where('journals.company_id',$companyId)->where('journal_lines.account_id',$accountId)->whereIn('journals.status',['posted','reversed'])->whereBetween('journals.entry_date',[$from,$to])->orderBy('journals.entry_date')->orderBy('journals.id')->select('journals.journal_number','journals.entry_date','journals.description','journal_lines.debit','journal_lines.credit','journal_lines.description as line_description')->get()->map(fn($r)=>(array)$r)->all();}
 public function profitAndLoss(int $companyId,string $from,string $to):array{return DB::table('journal_lines')->join('journals','journals.id','=','journal_lines.journal_id')->join('accounts','accounts.id','=','journal_lines.account_id')->where('journals.company_id',$companyId)->whereIn('journals.status',['posted','reversed'])->where('journals.exclude_from_profit_loss',false)->whereBetween('journals.entry_date',[$from,$to])->whereIn('accounts.type',['revenue','income','expense'])->groupBy('accounts.id','accounts.code','accounts.name_en','accounts.type')->orderBy('accounts.code')->selectRaw("accounts.code,accounts.name_en,accounts.type,SUM(CASE WHEN accounts.type IN ('revenue','income') THEN journal_lines.credit-journal_lines.debit ELSE journal_lines.debit-journal_lines.credit END) amount")->get()->map(fn($r)=>(array)$r)->all();}
 public function balanceSheet(int $companyId,string $asOf):array{return DB::table('journal_lines')->join('journals','journals.id','=','journal_lines.journal_id')->join('accounts','accounts.id','=','journal_lines.account_id')->where('journals.company_id',$companyId)->whereIn('journals.status',['posted','reversed'])->whereDate('journals.entry_date','<=',$asOf)->groupBy('accounts.id','accounts.code','accounts.name_en','accounts.type')->orderBy('accounts.code')->selectRaw("accounts.code,accounts.name_en,accounts.type,SUM(CASE WHEN accounts.normal_balance='debit' THEN journal_lines.debit-journal_lines.credit ELSE journal_lines.credit-journal_lines.debit END) amount")->get()->map(fn($r)=>(array)$r)->all();}
 public function agingReceivable(int $companyId,string $asOf):array{$rows=[];foreach(SalesInvoice::where('company_id',$companyId)->where('status','posted')->whereNull('credit_of_invoice_id')->whereDate('invoice_date','<=',$asOf)->with('contact')->get() as $i){$b=app(DocumentBalanceService::class)->sales($i,$asOf);if(Decimal::cmp($b['foreign'],'0')<=0)continue;$days=max(0,\Carbon\Carbon::parse($i->due_date?:$i->invoice_date)->diffInDays($asOf,false));$rows[]=['document'=>$i->invoice_number,'contact'=>$i->contact->name,'outstanding'=>$b['foreign'],'base_outstanding'=>$b['base'],'bucket'=>$days<=30?'0-30':($days<=60?'31-60':($days<=90?'61-90':'90+'))];}return $rows;}
 public function agingPayable(int $companyId,string $asOf):array{$rows=[];foreach(PurchaseBill::where('company_id',$companyId)->where('status','posted')->whereNull('credit_of_bill_id')->whereDate('bill_date','<=',$asOf)->with('contact')->get() as $i){$b=app(DocumentBalanceService::class)->purchase($i,$asOf);if(Decimal::cmp($b['foreign'],'0')<=0)continue;$days=max(0,\Carbon\Carbon::parse($i->due_date?:$i->bill_date)->diffInDays($asOf,false));$rows[]=['document'=>$i->bill_number,'contact'=>$i->contact->name,'outstanding'=>$b['foreign'],'base_outstanding'=>$b['base'],'bucket'=>$days<=30?'0-30':($days<=60?'31-60':($days<=90?'61-90':'90+'))];}return $rows;}
 public function taxSummary(int $companyId,string $from,string $to):array{$sales=DB::table('sales_invoice_lines')->join('sales_invoices','sales_invoices.id','=','sales_invoice_lines.sales_invoice_id')->where('sales_invoices.company_id',$companyId)->where('sales_invoices.status','posted')->whereBetween('sales_invoices.invoice_date',[$from,$to])->selectRaw('COALESCE(SUM(CASE WHEN sales_invoices.credit_of_invoice_id IS NULL THEN tax_amount ELSE -tax_amount END),0) total')->value('total');$purchase=DB::table('purchase_bill_lines')->join('purchase_bills','purchase_bills.id','=','purchase_bill_lines.purchase_bill_id')->where('purchase_bills.company_id',$companyId)->where('purchase_bills.status','posted')->whereBetween('purchase_bills.bill_date',[$from,$to])->selectRaw('COALESCE(SUM(CASE WHEN purchase_bills.credit_of_bill_id IS NULL THEN tax_amount ELSE -tax_amount END),0) total')->value('total');return ['sales_tax'=>Decimal::money((string)$sales),'purchase_tax'=>Decimal::money((string)$purchase),'net_tax'=>Decimal::sub((string)$sales,(string)$purchase)];}
}