<?php
namespace App\Services;
use App\Models\{SalesInvoice,SalesInvoiceLine,Contact,Account,Currency,Company,TaxCode};
use App\Support\Decimal;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class SalesService {
 public function createDraft(int $companyId,int $userId,array $data,array $lines):SalesInvoice{return DB::transaction(function()use($companyId,$userId,$data,$lines){$contact=Contact::where('company_id',$companyId)->whereKey($data['contact_id'])->whereIn('type',['customer','both'])->where('active',true)->firstOrFail();$currency=Currency::whereKey($data['currency_id'])->where('active',true)->firstOrFail();$calc=app(DocumentMathService::class)->calculate($companyId,$lines);$inv=SalesInvoice::create(['company_id'=>$companyId,'contact_id'=>$contact->id,'invoice_number'=>app(SequenceService::class)->next($companyId,!empty($data['credit_of_invoice_id'])?'sales_credit':'sales_invoice',!empty($data['credit_of_invoice_id'])?'SCN-':'INV-'),'invoice_date'=>$data['invoice_date'],'due_date'=>$data['due_date']??null,'currency_id'=>$currency->id,'exchange_rate'=>$data['exchange_rate']??'1','subtotal'=>$calc['subtotal'],'tax_total'=>$calc['tax_total'],'total'=>$calc['total'],'base_total'=>'0.000','status'=>'draft','credit_of_invoice_id'=>$data['credit_of_invoice_id']??null,'jofotara_required'=>false]);foreach($calc['lines'] as $l){$this->assertRevenueAccount($companyId,$l['revenue_account_id']);SalesInvoiceLine::create(['sales_invoice_id'=>$inv->id,'line_no'=>$l['line_no'],'description'=>$l['description'],'quantity'=>$l['quantity'],'unit_price'=>$l['unit_price'],'line_subtotal'=>$l['line_subtotal'],'revenue_account_id'=>$l['revenue_account_id'],'tax_code_id'=>$l['tax_code_id']??null,'tax_amount'=>$l['tax_amount']]);}return $inv->fresh('lines');});}
 public function createCredit(SalesInvoice $original,int $userId,array $data,array $lines):SalesInvoice{return DB::transaction(function()use($original,$userId,$data,$lines){$original=SalesInvoice::whereKey($original->id)->lockForUpdate()->firstOrFail();if($original->status!=='posted'||$original->credit_of_invoice_id)throw ValidationException::withMessages(['invoice'=>'Only posted original invoices may be credited.']);$data['contact_id']=$original->contact_id;$data['currency_id']=$original->currency_id;$data['credit_of_invoice_id']=$original->id;$out=app(DocumentBalanceService::class)->sales($original,$data['invoice_date']);$credit=$this->createDraft($original->company_id,$userId,$data,$lines);if(Decimal::cmp($credit->total,$out['foreign'])>0)throw ValidationException::withMessages(['total'=>'Credit exceeds outstanding invoice amount.']);return $credit;});}
 public function post(SalesInvoice $invoice,int $userId):SalesInvoice{return DB::transaction(function()use($invoice,$userId){$invoice=SalesInvoice::whereKey($invoice->id)->lockForUpdate()->with(['lines'])->firstOrFail();if($invoice->status!=='draft')throw ValidationException::withMessages(['invoice'=>'Invoice is not draft.']);app(PeriodService::class)->forDate($invoice->company_id,$invoice->invoice_date,true);$company=Company::findOrFail($invoice->company_id);$contact=Contact::where('company_id',$invoice->company_id)->findOrFail($invoice->contact_id);$control=$contact->receivable_account_id?:$company->ar_control_account_id;$this->assertAccount($invoice->company_id,$control,'AR control account');$journalLines=[];$base='0.000';foreach($invoice->lines as $l){$this->assertRevenueAccount($invoice->company_id,$l->revenue_account_id);$v=Decimal::mul($l->line_subtotal,$invoice->exchange_rate);$base=Decimal::add($base,$v);$journalLines[]=['account_id'=>$l->revenue_account_id,'description'=>$l->description,'debit'=>$invoice->credit_of_invoice_id?$v:'0','credit'=>$invoice->credit_of_invoice_id?'0':$v];if(Decimal::cmp($l->tax_amount,'0')>0){$tax=TaxCode::where('company_id',$invoice->company_id)->findOrFail($l->tax_code_id);$taxAcc=$tax->sales_account_id?:$company->sales_tax_account_id;$this->assertAccount($invoice->company_id,$taxAcc,'sales tax account');$tv=Decimal::mul($l->tax_amount,$invoice->exchange_rate);$base=Decimal::add($base,$tv);$journalLines[]=['account_id'=>$taxAcc,'description'=>'Sales tax','debit'=>$invoice->credit_of_invoice_id?$tv:'0','credit'=>$invoice->credit_of_invoice_id?'0':$tv];}}
  array_unshift($journalLines,['account_id'=>$control,'description'=>$invoice->invoice_number,'debit'=>$invoice->credit_of_invoice_id?'0':$base,'credit'=>$invoice->credit_of_invoice_id?$base:'0','currency_id'=>$invoice->currency_id,'exchange_rate'=>$invoice->exchange_rate,'foreign_amount'=>$invoice->credit_of_invoice_id?('-'.$invoice->total):$invoice->total]);$j=app(JournalService::class)->createDraft($invoice->company_id,$userId,(string)$invoice->invoice_date,'Sales '.$invoice->invoice_number,$journalLines,['source_type'=>$invoice->credit_of_invoice_id?'sales_credit':'sales_invoice','source_id'=>$invoice->id]);$j=app(JournalService::class)->post($j,$userId);$invoice->update(['status'=>'posted','journal_id'=>$j->id,'control_account_id'=>$control,'base_total'=>$base]);app(AuditService::class)->record('sales.posted',$invoice,['status'=>'draft'],['status'=>'posted','journal_id'=>$j->id],$invoice->company_id,$userId);return $invoice->fresh('lines');});}
 private function assertRevenueAccount(int $companyId,int $accountId):void{$a=Account::where('company_id',$companyId)->findOrFail($accountId);if(!$a->active||!$a->is_postable||!in_array($a->type,['revenue','income']))throw ValidationException::withMessages(['account'=>'Sales lines require an active postable revenue account.']);}
 private function assertAccount(int $companyId,?int $id,string $label):void{if(!$id||!Account::where('company_id',$companyId)->whereKey($id)->where('active',true)->where('is_postable',true)->exists())throw ValidationException::withMessages(['account'=>$label.' is not configured correctly.']);}
}