<?php
namespace App\Services;
use App\Models\{FiscalYear,Account,Journal,Company};
use App\Support\Decimal;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class YearEndService {
 public function close(FiscalYear $fy,int $userId,string $reason='Year-end close'):?Journal{return DB::transaction(function()use($fy,$userId,$reason){$fy=FiscalYear::whereKey($fy->id)->lockForUpdate()->firstOrFail();if($fy->status!=='open')throw ValidationException::withMessages(['fiscal_year'=>'Fiscal year is not open.']);if($fy->periods()->where('status','open')->exists())throw ValidationException::withMessages(['fiscal_year'=>'Close all accounting periods before fiscal-year close.']);$company=Company::findOrFail($fy->company_id);if(!$company->retained_earnings_account_id)throw ValidationException::withMessages(['account'=>'Retained earnings account is not configured.']);$balances=DB::table('journal_lines')->join('journals','journals.id','=','journal_lines.journal_id')->join('accounts','accounts.id','=','journal_lines.account_id')->where('journals.company_id',$fy->company_id)->whereIn('journals.status',['posted','reversed'])->whereBetween('journals.entry_date',[$fy->start_date,$fy->end_date])->where('journals.exclude_from_profit_loss',false)->whereIn('accounts.type',['revenue','income','expense'])->groupBy('accounts.id','accounts.type')->selectRaw('accounts.id, accounts.type, SUM(journal_lines.debit-journal_lines.credit) as net')->get();$lines=[];$retained='0.000';foreach($balances as $b){$net=Decimal::money((string)$b->net);if(Decimal::cmp($net,'0')===0)continue;if(Decimal::cmp($net,'0')>0){$lines[]=['account_id'=>$b->id,'debit'=>'0','credit'=>$net];$retained=Decimal::add($retained,$net);}else{$v=Decimal::abs($net);$lines[]=['account_id'=>$b->id,'debit'=>$v,'credit'=>'0'];$retained=Decimal::sub($retained,$v);}}if(!$lines){$fy->update(['status'=>'closed','closed_by'=>$userId,'closed_at'=>now(),'close_reason'=>$reason]);app(AuditService::class)->record('fiscal_year.closed',$fy,null,['journal_id'=>null],$fy->company_id,$userId);return null;}if(Decimal::cmp($retained,'0')>0)$lines[]=['account_id'=>$company->retained_earnings_account_id,'debit'=>$retained,'credit'=>'0'];else$lines[]=['account_id'=>$company->retained_earnings_account_id,'debit'=>'0','credit'=>Decimal::abs($retained)];$date=(string)$fy->end_date;$period=$fy->periods()->orderByDesc('end_date')->firstOrFail();$was=$period->status;$period->status='open';$period->save();try{$j=app(JournalService::class)->createDraft($fy->company_id,$userId,$date,'Year-end closing',$lines,['source_type'=>'year_end_close','source_id'=>$fy->id,'exclude_from_profit_loss'=>true]);$j=app(JournalService::class)->post($j,$userId);}finally{$period->status=$was;$period->save();}$fy->update(['status'=>'closed','closing_journal_id'=>$j->id,'closed_by'=>$userId,'closed_at'=>now(),'close_reason'=>$reason]);app(AuditService::class)->record('fiscal_year.closed',$fy,null,['journal_id'=>$j->id],$fy->company_id,$userId);return $j;});}
 public function reopen(FiscalYear $fy,int $userId,string $date,string $reason):?Journal{return DB::transaction(function()use($fy,$userId,$date,$reason){$fy=FiscalYear::whereKey($fy->id)->lockForUpdate()->firstOrFail();if($fy->status!=='closed')throw ValidationException::withMessages(['fiscal_year'=>'Fiscal year is not closed.']);if(trim($reason)==='')throw ValidationException::withMessages(['reason'=>'Reason is required.']);$rev=null;if($fy->closing_journal_id)$rev=app(JournalService::class)->reverse(Journal::findOrFail($fy->closing_journal_id),$userId,$date,$reason);$fy->update(['status'=>'open','closing_journal_id'=>null,'closed_by'=>null,'closed_at'=>null,'close_reason'=>null]);app(AuditService::class)->record('fiscal_year.reopened',$fy,['status'=>'closed'],['status'=>'open','reason'=>$reason],$fy->company_id,$userId);return $rev;});}
}