<?php
namespace Tests\Feature;
use Tests\TestCase;use Tests\CreatesLedgerCompany;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use App\Services\{JournalService,PeriodService,IntegrityService};use App\Models\Journal;use Illuminate\Support\Facades\DB;
class JournalEngineTest extends TestCase {use RefreshDatabase,CreatesLedgerCompany;
 public function test_balanced_journal_posts_and_integrity_check_passes():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$j=app(JournalService::class)->createDraft($c->id,$u->id,'2026-02-01','sale',[['account_id'=>$a['1110']->id,'debit'=>'100.000','credit'=>'0'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'100.000']]);$j=app(JournalService::class)->post($j,$u->id);$this->assertSame('posted',$j->status);$this->assertSame([],app(IntegrityService::class)->check($c->id));}
 public function test_unbalanced_and_double_sided_lines_are_rejected():void{[$c,$u,$a]=$this->company();$this->actingAs($u);foreach([[['account_id'=>$a['1110']->id,'debit'=>'100','credit'=>'0'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'99']],[['account_id'=>$a['1110']->id,'debit'=>'100','credit'=>'1'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'99']]] as $lines){$j=app(JournalService::class)->createDraft($c->id,$u->id,'2026-02-02','bad',$lines);try{app(JournalService::class)->post($j,$u->id);$this->fail('Expected validation failure');}catch(ValidationException){$this->assertSame('draft',$j->fresh()->status);}}}
 public function test_closed_period_rejects_posting():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$j=app(JournalService::class)->createDraft($c->id,$u->id,'2026-03-01','draft',[['account_id'=>$a['1110']->id,'debit'=>'10','credit'=>'0'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'10']]);$p=$j->period; $j->delete(); app(PeriodService::class)->close($p,$u->id);$j=app(JournalService::class)->createDraft($c->id,$u->id,'2026-03-02','draft',[['account_id'=>$a['1110']->id,'debit'=>'10','credit'=>'0'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'10']]);$this->expectException(ValidationException::class);app(JournalService::class)->post($j,$u->id);}
 public function test_reversal_is_additive_and_posted_history_cannot_be_edited():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$j=app(JournalService::class)->createDraft($c->id,$u->id,'2026-04-01','original',[['account_id'=>$a['1110']->id,'debit'=>'50','credit'=>'0'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'50']]);$j=app(JournalService::class)->post($j,$u->id);$rev=app(JournalService::class)->reverse($j,$u->id,'2026-04-02','mistake');$this->assertSame('reversed',$j->fresh()->status);$this->assertSame($j->id,$rev->reversal_of_journal_id);$net=DB::table('journal_lines')->join('journals','journals.id','=','journal_lines.journal_id')->whereIn('journals.id',[$j->id,$rev->id])->sum(DB::raw('debit-credit'));$this->assertEqualsWithDelta(0,(float)$net,0.0001);$this->expectException(\Throwable::class);$j->fresh()->update(['description'=>'tampered']);}
 public function test_nonpostable_and_cross_company_accounts_are_rejected():void{[$c,$u,$a]=$this->company();[$other]=$this->company();$otherCash=\App\Models\Account::where('company_id',$other->id)->where('code','1110')->first();$this->actingAs($u);foreach([$a['1000']->id,$otherCash->id] as $bad){$j=app(JournalService::class)->createDraft($c->id,$u->id,'2026-05-01','bad',[['account_id'=>$bad,'debit'=>'10','credit'=>'0'],['account_id'=>$a['4100']->id,'debit'=>'0','credit'=>'10']]);try{app(JournalService::class)->post($j,$u->id);$this->fail('Expected invalid account');}catch(ValidationException){$this->assertTrue(true);}}}
}
