<?php
namespace Tests\Feature;
use Tests\TestCase;use Tests\CreatesLedgerCompany;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use App\Services\{SalesService,PurchaseService,PaymentService,DocumentBalanceService};use App\Models\{SalesInvoice,PurchaseBill,Payment};
class SalesPurchasePaymentTest extends TestCase {use RefreshDatabase,CreatesLedgerCompany;
 private function salesInvoice($c,$u,$a,$customer,$amount='100.000',$date='2026-06-01',$currencyId=null,$rate='1'){ $currencyId??=$c->base_currency_id;$i=app(SalesService::class)->createDraft($c->id,$u->id,['contact_id'=>$customer->id,'invoice_date'=>$date,'currency_id'=>$currencyId,'exchange_rate'=>$rate],[['description'=>'Service','quantity'=>'1','unit_price'=>$amount,'revenue_account_id'=>$a['4100']->id]]);return app(SalesService::class)->post($i,$u->id);}
 private function purchaseBill($c,$u,$a,$supplier,$amount='80.000',$date='2026-06-01',$currencyId=null,$rate='1'){ $currencyId??=$c->base_currency_id;$b=app(PurchaseService::class)->createDraft($c->id,$u->id,['contact_id'=>$supplier->id,'bill_date'=>$date,'currency_id'=>$currencyId,'exchange_rate'=>$rate],[['description'=>'Expense','quantity'=>'1','unit_price'=>$amount,'expense_account_id'=>$a['5100']->id]]);return app(PurchaseService::class)->post($b,$u->id);}
 public function test_sales_and_purchase_post_to_frozen_control_accounts():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$customer=$this->customer($c);$supplier=$this->supplier($c);$i=$this->salesInvoice($c,$u,$a,$customer);$b=$this->purchaseBill($c,$u,$a,$supplier);$this->assertSame($a['1200']->id,$i->control_account_id);$this->assertSame($a['2100']->id,$b->control_account_id);$newAr=\App\Models\Account::create(['company_id'=>$c->id,'code'=>'1210','name_en'=>'Other AR','type'=>'asset','normal_balance'=>'debit','is_postable'=>true,'active'=>true]);$c->update(['ar_control_account_id'=>$newAr->id]);$this->assertSame($a['1200']->id,$i->fresh()->control_account_id);}
 public function test_credit_cannot_exceed_outstanding_and_failure_leaves_no_draft():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$customer=$this->customer($c);$i=$this->salesInvoice($c,$u,$a,$customer,'100');$before=SalesInvoice::count();try{app(SalesService::class)->createCredit($i,$u->id,['invoice_date'=>'2026-06-02','exchange_rate'=>'1'],[['description'=>'Too much','quantity'=>'1','unit_price'=>'101','revenue_account_id'=>$a['4100']->id]]);$this->fail('Expected validation');}catch(ValidationException){$this->assertSame($before,SalesInvoice::count());}}
 public function test_receipt_allocation_cannot_overpay_and_historical_balance_ignores_future_payment():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$customer=$this->customer($c);$i=$this->salesInvoice($c,$u,$a,$customer,'100','2026-06-01');$data=['contact_id'=>$customer->id,'payment_date'=>'2026-07-01','currency_id'=>$c->base_currency_id,'amount'=>'40','exchange_rate'=>'1','cash_account_id'=>$a['1110']->id];$p=app(PaymentService::class)->receive($c->id,$u->id,$data,[['document_id'=>$i->id,'amount'=>'40']]);$this->assertSame('100.000',app(DocumentBalanceService::class)->sales($i,'2026-06-30')['foreign']);$this->assertSame('60.000',app(DocumentBalanceService::class)->sales($i,'2026-07-01')['foreign']);$data['amount']='61';try{app(PaymentService::class)->receive($c->id,$u->id,$data,[['document_id'=>$i->id,'amount'=>'61']]);$this->fail('Expected over-allocation failure');}catch(ValidationException){$this->assertTrue(true);}}
 public function test_void_is_reversal_and_historical_as_of_before_void_still_counts_payment():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$customer=$this->customer($c);$i=$this->salesInvoice($c,$u,$a,$customer,'100','2026-06-01');$p=app(PaymentService::class)->receive($c->id,$u->id,['contact_id'=>$customer->id,'payment_date'=>'2026-06-10','currency_id'=>$c->base_currency_id,'amount'=>'100','exchange_rate'=>'1','cash_account_id'=>$a['1110']->id],[['document_id'=>$i->id,'amount'=>'100']]);app(PaymentService::class)->void($p,$u->id,'2026-07-01','returned');$this->assertSame('0.000',app(DocumentBalanceService::class)->sales($i,'2026-06-30')['foreign']);$this->assertSame('100.000',app(DocumentBalanceService::class)->sales($i,'2026-07-01')['foreign']);$this->assertSame('voided',$p->fresh()->status);$this->assertNotNull($p->fresh()->reversal_journal_id);}
 public function test_supplier_payment_posts_and_clears_bill():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$supplier=$this->supplier($c);$b=$this->purchaseBill($c,$u,$a,$supplier,'80');$p=app(PaymentService::class)->paySupplier($c->id,$u->id,['contact_id'=>$supplier->id,'payment_date'=>'2026-06-03','currency_id'=>$c->base_currency_id,'amount'=>'80','exchange_rate'=>'1','cash_account_id'=>$a['1110']->id],[['document_id'=>$b->id,'amount'=>'80']]);$this->assertSame('0.000',app(DocumentBalanceService::class)->purchase($b,'2026-06-03')['foreign']);$this->assertSame('posted',$p->status);}
}
