<?php
namespace Tests\Feature;
use Tests\TestCase;use Tests\CreatesLedgerCompany;use Illuminate\Foundation\Testing\RefreshDatabase;use App\Services\JournalService;use App\Models\{Role,Permission,User};
class SecurityIsolationTest extends TestCase {use RefreshDatabase,CreatesLedgerCompany;
 public function test_route_model_binding_cannot_read_another_company_journal():void{[$a,$ua,$aa]=$this->company();[$b,$ub,$ab]=$this->company();$this->actingAs($ub);$j=app(JournalService::class)->createDraft($b->id,$ub->id,'2026-02-01','secret',[['account_id'=>$ab['1110']->id,'debit'=>'1','credit'=>'0'],['account_id'=>$ab['4100']->id,'debit'=>'0','credit'=>'1']]);$this->actingAs($ua)->get('/journals/'.$j->id)->assertNotFound();}
 public function test_permission_middleware_denies_user_without_permission():void{[$c,$admin]=$this->company();$role=Role::create(['company_id'=>$c->id,'name'=>'Viewer','slug'=>'viewer']);$role->permissions()->attach(Permission::where('slug','dashboard.view')->value('id'));$u=User::create(['company_id'=>$c->id,'name'=>'Viewer','email'=>'viewer@example.com','password'=>'Password-Strong-123','active'=>true]);$u->roles()->attach($role);$this->actingAs($u)->get('/')->assertOk();$this->actingAs($u)->get('/accounts')->assertForbidden();}
 public function test_security_headers_are_present():void{[$c,$u]=$this->company();$r=$this->actingAs($u)->get('/');$r->assertHeader('X-Content-Type-Options','nosniff')->assertHeader('X-Frame-Options','DENY')->assertHeader('Referrer-Policy','strict-origin-when-cross-origin');}
 public function test_posted_document_database_trigger_blocks_direct_mutation():void{[$c,$u,$a]=$this->company();$this->actingAs($u);$customer=$this->customer($c);$i=app(\App\Services\SalesService::class)->createDraft($c->id,$u->id,['contact_id'=>$customer->id,'invoice_date'=>'2026-03-01','currency_id'=>$c->base_currency_id,'exchange_rate'=>'1'],[['description'=>'Sale','quantity'=>'1','unit_price'=>'10','revenue_account_id'=>$a['4100']->id]]);$i=app(\App\Services\SalesService::class)->post($i,$u->id);$this->expectException(\Throwable::class);$i->update(['total'=>'999.000']);}
}
