<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
return new class extends Migration {
 public function up(): void {$d=DB::getDriverName();if($d==='sqlite'){
  DB::unprepared("CREATE TRIGGER sales_invoices_immutable BEFORE UPDATE ON sales_invoices WHEN OLD.status='posted' BEGIN SELECT RAISE(ABORT,'posted sales invoices are immutable'); END;");
  DB::unprepared("CREATE TRIGGER sales_invoices_nodelete BEFORE DELETE ON sales_invoices WHEN OLD.status<>'draft' BEGIN SELECT RAISE(ABORT,'posted sales invoices are immutable'); END;");
  DB::unprepared("CREATE TRIGGER purchase_bills_immutable BEFORE UPDATE ON purchase_bills WHEN OLD.status='posted' BEGIN SELECT RAISE(ABORT,'posted purchase bills are immutable'); END;");
  DB::unprepared("CREATE TRIGGER purchase_bills_nodelete BEFORE DELETE ON purchase_bills WHEN OLD.status<>'draft' BEGIN SELECT RAISE(ABORT,'posted purchase bills are immutable'); END;");
  DB::unprepared("CREATE TRIGGER payments_immutable BEFORE UPDATE OF company_id,contact_id,payment_number,type,payment_date,currency_id,amount,exchange_rate,base_amount,cash_account_id,journal_id,created_by ON payments WHEN OLD.status='posted' BEGIN SELECT RAISE(ABORT,'posted payments are immutable'); END;");
  DB::unprepared("CREATE TRIGGER payments_status BEFORE UPDATE OF status ON payments WHEN (OLD.status='posted' AND NEW.status NOT IN ('posted','voided')) OR (OLD.status='voided' AND NEW.status<>'voided') BEGIN SELECT RAISE(ABORT,'invalid payment transition'); END;");
  DB::unprepared("CREATE TRIGGER payments_nodelete BEFORE DELETE ON payments WHEN OLD.status<>'draft' BEGIN SELECT RAISE(ABORT,'posted payments are immutable'); END;");
  DB::unprepared("CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_logs BEGIN SELECT RAISE(ABORT,'audit log is append-only'); END;");DB::unprepared("CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_logs BEGIN SELECT RAISE(ABORT,'audit log is append-only'); END;");return;}
 if($d==='mysql'){
  foreach([['sales_invoices','status','posted'],['purchase_bills','status','posted']] as [$table,$col,$value]){DB::unprepared("CREATE TRIGGER {$table}_immutable BEFORE UPDATE ON {$table} FOR EACH ROW BEGIN IF OLD.{$col}='{$value}' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='posted document is immutable'; END IF; END");DB::unprepared("CREATE TRIGGER {$table}_nodelete BEFORE DELETE ON {$table} FOR EACH ROW BEGIN IF OLD.status<>'draft' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='posted document is immutable'; END IF; END");}
  DB::unprepared("CREATE TRIGGER payments_immutable BEFORE UPDATE ON payments FOR EACH ROW BEGIN IF OLD.status='posted' AND (NOT (NEW.company_id <=> OLD.company_id) OR NOT (NEW.contact_id <=> OLD.contact_id) OR NOT (NEW.payment_number <=> OLD.payment_number) OR NOT (NEW.type <=> OLD.type) OR NOT (NEW.payment_date <=> OLD.payment_date) OR NOT (NEW.currency_id <=> OLD.currency_id) OR NOT (NEW.amount <=> OLD.amount) OR NOT (NEW.exchange_rate <=> OLD.exchange_rate) OR NOT (NEW.base_amount <=> OLD.base_amount) OR NOT (NEW.cash_account_id <=> OLD.cash_account_id) OR NOT (NEW.journal_id <=> OLD.journal_id) OR NOT (NEW.created_by <=> OLD.created_by)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='posted payment is immutable'; END IF; IF OLD.status='posted' AND NEW.status NOT IN ('posted','voided') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid payment transition'; END IF; IF OLD.status='voided' AND NEW.status <> 'voided' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='invalid payment transition'; END IF; END");
  DB::unprepared("CREATE TRIGGER payments_nodelete BEFORE DELETE ON payments FOR EACH ROW BEGIN IF OLD.status<>'draft' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='posted payment is immutable'; END IF; END");
  DB::unprepared("CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_logs FOR EACH ROW BEGIN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='audit log is append-only'; END");DB::unprepared("CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_logs FOR EACH ROW BEGIN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='audit log is append-only'; END");
 }}
 public function down():void{foreach(['sales_invoices_immutable','sales_invoices_nodelete','purchase_bills_immutable','purchase_bills_nodelete','payments_immutable','payments_status','payments_nodelete','audit_no_update','audit_no_delete'] as $x)DB::unprepared('DROP TRIGGER IF EXISTS '.$x);}
};
