<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('currencies', function(Blueprint $t){$t->id();$t->char('code',3)->unique();$t->string('name');$t->unsignedTinyInteger('decimal_places')->default(3);$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('companies', function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->foreignId('base_currency_id')->constrained('currencies')->restrictOnDelete();$t->string('tax_number')->nullable();$t->string('registration_number')->nullable();$t->string('phone')->nullable();$t->string('email')->nullable();$t->string('address')->nullable();$t->timestamps();});
  Schema::create('users', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('email');$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->boolean('active')->default(true);$t->rememberToken();$t->timestamps();$t->unique(['company_id','email']);});
  Schema::create('password_reset_tokens', function(Blueprint $t){$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
  Schema::create('sessions', function(Blueprint $t){$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
  Schema::create('roles', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('slug');$t->timestamps();$t->unique(['company_id','slug']);});
  Schema::create('permissions', function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->timestamps();});
  Schema::create('permission_role', function(Blueprint $t){$t->foreignId('permission_id')->constrained()->cascadeOnDelete();$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->primary(['permission_id','role_id']);});
  Schema::create('role_user', function(Blueprint $t){$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->primary(['role_id','user_id']);});
  Schema::create('fiscal_years', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->unsignedSmallInteger('year');$t->date('start_date');$t->date('end_date');$t->string('status')->default('open');$t->foreignId('closing_journal_id')->nullable();$t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('closed_at')->nullable();$t->text('close_reason')->nullable();$t->timestamps();$t->unique(['company_id','year']);});
  Schema::create('accounting_periods', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('fiscal_year_id')->constrained()->restrictOnDelete();$t->string('name');$t->date('start_date');$t->date('end_date');$t->string('status')->default('open');$t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('closed_at')->nullable();$t->foreignId('reopened_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reopened_at')->nullable();$t->text('reopen_reason')->nullable();$t->timestamps();$t->unique(['company_id','start_date','end_date']);});
  Schema::create('accounts', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('parent_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->string('code');$t->string('name_en');$t->string('name_ar')->nullable();$t->string('type');$t->string('normal_balance');$t->boolean('is_postable')->default(true);$t->boolean('active')->default(true);$t->timestamps();$t->unique(['company_id','code']);});
  Schema::table('companies', function(Blueprint $t){foreach(['retained_earnings_account_id','fx_gain_account_id','fx_loss_account_id','ar_control_account_id','ap_control_account_id','sales_tax_account_id','purchase_tax_account_id'] as $c) $t->foreignId($c)->nullable()->constrained('accounts')->restrictOnDelete();});
  Schema::create('sequences', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->string('key');$t->unsignedBigInteger('next_value')->default(1);$t->timestamps();$t->unique(['company_id','key']);});
  Schema::create('journals', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('accounting_period_id')->nullable()->constrained()->restrictOnDelete();$t->string('journal_number');$t->date('entry_date');$t->text('description')->nullable();$t->string('status')->default('draft');$t->string('source_type')->nullable();$t->unsignedBigInteger('source_id')->nullable();$t->boolean('exclude_from_profit_loss')->default(false);$t->foreignId('reversal_of_journal_id')->nullable()->constrained('journals')->restrictOnDelete();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->foreignId('posted_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('posted_at')->nullable();$t->timestamp('reversed_at')->nullable();$t->timestamps();$t->unique(['company_id','journal_number']);$t->index(['company_id','entry_date','status']);});
  Schema::table('fiscal_years', fn(Blueprint $t)=>$t->foreign('closing_journal_id')->references('id')->on('journals')->restrictOnDelete());
  Schema::create('journal_lines', function(Blueprint $t){$t->id();$t->foreignId('journal_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('line_no');$t->foreignId('account_id')->constrained('accounts')->restrictOnDelete();$t->string('description')->nullable();$t->decimal('debit',18,3)->default(0);$t->decimal('credit',18,3)->default(0);$t->foreignId('currency_id')->nullable()->constrained('currencies')->restrictOnDelete();$t->decimal('exchange_rate',20,10)->nullable();$t->decimal('foreign_amount',20,6)->nullable();$t->timestamps();$t->unique(['journal_id','line_no']);$t->index(['account_id','journal_id']);});
  Schema::create('contacts', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->string('type');$t->string('name');$t->string('tax_number')->nullable();$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('address')->nullable();$t->foreignId('receivable_account_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->foreignId('payable_account_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->boolean('active')->default(true);$t->timestamps();$t->softDeletes();});
  Schema::create('tax_codes', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->string('code');$t->string('name');$t->decimal('rate',8,5);$t->string('type')->default('both');$t->foreignId('sales_account_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->foreignId('purchase_account_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->boolean('active')->default(true);$t->timestamps();$t->unique(['company_id','code']);});
  Schema::create('exchange_rates', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('currency_id')->constrained('currencies')->restrictOnDelete();$t->date('rate_date');$t->decimal('rate',20,10);$t->string('source')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['company_id','currency_id','rate_date']);});
  Schema::create('sales_invoices', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('contact_id')->constrained('contacts')->restrictOnDelete();$t->string('invoice_number');$t->date('invoice_date');$t->date('due_date')->nullable();$t->foreignId('currency_id')->constrained('currencies')->restrictOnDelete();$t->decimal('exchange_rate',20,10)->default(1);$t->decimal('subtotal',18,3)->default(0);$t->decimal('tax_total',18,3)->default(0);$t->decimal('total',18,3)->default(0);$t->decimal('base_total',18,3)->default(0);$t->string('status')->default('draft');$t->foreignId('control_account_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->foreignId('journal_id')->nullable()->constrained('journals')->restrictOnDelete();$t->foreignId('credit_of_invoice_id')->nullable()->constrained('sales_invoices')->restrictOnDelete();$t->boolean('jofotara_required')->default(false);$t->timestamps();$t->unique(['company_id','invoice_number']);});
  Schema::create('sales_invoice_lines', function(Blueprint $t){$t->id();$t->foreignId('sales_invoice_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('line_no');$t->text('description');$t->decimal('quantity',18,4);$t->decimal('unit_price',18,6);$t->decimal('line_subtotal',18,3);$t->foreignId('revenue_account_id')->constrained('accounts')->restrictOnDelete();$t->foreignId('tax_code_id')->nullable()->constrained('tax_codes')->restrictOnDelete();$t->decimal('tax_amount',18,3)->default(0);$t->timestamps();$t->unique(['sales_invoice_id','line_no']);});
  Schema::create('purchase_bills', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('contact_id')->constrained('contacts')->restrictOnDelete();$t->string('bill_number');$t->string('supplier_reference')->nullable();$t->date('bill_date');$t->date('due_date')->nullable();$t->foreignId('currency_id')->constrained('currencies')->restrictOnDelete();$t->decimal('exchange_rate',20,10)->default(1);$t->decimal('subtotal',18,3)->default(0);$t->decimal('tax_total',18,3)->default(0);$t->decimal('total',18,3)->default(0);$t->decimal('base_total',18,3)->default(0);$t->string('status')->default('draft');$t->foreignId('control_account_id')->nullable()->constrained('accounts')->restrictOnDelete();$t->foreignId('journal_id')->nullable()->constrained('journals')->restrictOnDelete();$t->foreignId('credit_of_bill_id')->nullable()->constrained('purchase_bills')->restrictOnDelete();$t->timestamps();$t->unique(['company_id','bill_number']);});
  Schema::create('purchase_bill_lines', function(Blueprint $t){$t->id();$t->foreignId('purchase_bill_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('line_no');$t->text('description');$t->decimal('quantity',18,4);$t->decimal('unit_price',18,6);$t->decimal('line_subtotal',18,3);$t->foreignId('expense_account_id')->constrained('accounts')->restrictOnDelete();$t->foreignId('tax_code_id')->nullable()->constrained('tax_codes')->restrictOnDelete();$t->decimal('tax_amount',18,3)->default(0);$t->timestamps();$t->unique(['purchase_bill_id','line_no']);});
  Schema::create('payments', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('contact_id')->constrained('contacts')->restrictOnDelete();$t->string('payment_number');$t->string('type');$t->date('payment_date');$t->foreignId('currency_id')->constrained('currencies')->restrictOnDelete();$t->decimal('amount',18,3);$t->decimal('exchange_rate',20,10)->default(1);$t->decimal('base_amount',18,3);$t->foreignId('cash_account_id')->constrained('accounts')->restrictOnDelete();$t->string('status')->default('posted');$t->date('void_date')->nullable();$t->timestamp('voided_at')->nullable();$t->foreignId('journal_id')->nullable()->constrained('journals')->restrictOnDelete();$t->foreignId('reversal_journal_id')->nullable()->constrained('journals')->restrictOnDelete();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['company_id','payment_number']);});
  Schema::create('payment_allocations', function(Blueprint $t){$t->id();$t->foreignId('payment_id')->constrained()->restrictOnDelete();$t->string('allocatable_type');$t->unsignedBigInteger('allocatable_id');$t->decimal('amount',18,3);$t->decimal('base_amount',18,3);$t->decimal('realized_fx',18,3)->default(0);$t->timestamps();$t->index(['allocatable_type','allocatable_id']);});
  Schema::create('fx_revaluation_items', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('journal_id')->constrained('journals')->restrictOnDelete();$t->string('revaluable_type');$t->unsignedBigInteger('revaluable_id');$t->foreignId('currency_id')->constrained('currencies')->restrictOnDelete();$t->date('revaluation_date');$t->decimal('foreign_outstanding',18,6);$t->decimal('previous_carrying_base',18,3);$t->decimal('target_carrying_base',18,3);$t->decimal('carrying_adjustment',18,3);$t->timestamps();$t->index(['company_id','revaluable_type','revaluable_id','revaluation_date'],'fx_reval_lookup');});
  Schema::create('company_integrations', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->string('provider');$t->boolean('enabled')->default(false);$t->text('encrypted_credentials')->nullable();$t->timestamps();$t->unique(['company_id','provider']);});
  Schema::create('jofotara_submissions', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->restrictOnDelete();$t->foreignId('sales_invoice_id')->constrained()->restrictOnDelete();$t->string('status');$t->uuid('request_uuid')->unique();$t->string('government_invoice_id')->nullable();$t->unsignedInteger('attempt_no')->default(1);$t->longText('request_payload')->nullable();$t->longText('response_payload')->nullable();$t->text('error_message')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->index(['company_id','sales_invoice_id','status']);});
  Schema::create('audit_logs', function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('event');$t->string('auditable_type')->nullable();$t->unsignedBigInteger('auditable_id')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->timestamps();$t->index(['company_id','event']);$t->index(['auditable_type','auditable_id']);});
 }
 public function down(): void {
  Schema::table('fiscal_years', fn(Blueprint $t)=>$t->dropForeign(['closing_journal_id']));
  Schema::table('companies', function(Blueprint $t){foreach(['retained_earnings_account_id','fx_gain_account_id','fx_loss_account_id','ar_control_account_id','ap_control_account_id','sales_tax_account_id','purchase_tax_account_id'] as $c)$t->dropForeign([$c]);});
  foreach(['audit_logs','jofotara_submissions','company_integrations','fx_revaluation_items','payment_allocations','payments','purchase_bill_lines','purchase_bills','sales_invoice_lines','sales_invoices','exchange_rates','tax_codes','contacts','journal_lines','journals','sequences','accounts','accounting_periods','fiscal_years','role_user','permission_role','permissions','roles','sessions','password_reset_tokens','users','companies','currencies'] as $x) Schema::dropIfExists($x);
 }
};